# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c66ffecb8d2c4db810e78eef357365a9195eb5a0dc93d1f9bf68ce7c70d9bb32f595f9d709a44d95b404626fe4396d294d29caa2887ddbc81c8587761af59cd5

test:
  secret_key_base: c2d3e0b50b1e9646233055aef71748f7e4ceb57f045c1af63dab6ab9fa8097fd5b4426978148196ec007efb61aff1243293781d08b19da0c903cc07c08db2416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
